image:
  repository: defendersd/defender.job-scheduler
  tag: 20260111-36
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-job-scheduler
      paths:
        - path: /
          pathType: Prefix
