image:
  repository: defendersd/defender.portal
  tag: 20260128-48
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-portal
      paths:
        - path: /
          pathType: Prefix
