image:
  repository: defendersd/defender.budget-tracker
  tag: 20260122-45
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-budget-tracker
      paths:
        - path: /
          pathType: Prefix
