image:
  repository: defendersd/defender.wallet
  tag: 20260115-41
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-wallet
      paths:
        - path: /
          pathType: Prefix
