image:
  repository: defendersd/defender.notification
  tag: 20260111-38
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-notification
      paths:
        - path: /
          pathType: Prefix
