image:
  repository: defendersd/defender.risk-games
  tag: 20260111-38
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-risk-games
      paths:
        - path: /
          pathType: Prefix
