image:
  repository: defendersd/defender.user-management
  tag: 20260111-36
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-user-management
      paths:
        - path: /
          pathType: Prefix
