image:
  repository: defendersd/defender.identity
  tag: 20260125-47
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-identity
      paths:
        - path: /
          pathType: Prefix
