image:
  repository: defendersd/dev-budget-tracker-service
  tag: latest
  pullPolicy: Always

replicaCount: 3

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-budget-tracker
      paths:
        - path: /
          pathType: Prefix
