image:
  repository: defendersd/portal
  tag: 20260111-31
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-portal
      paths:
        - path: /
          pathType: Prefix
